name:                advent2021
version:             0.1.0.0
author:              "Alexander Chernoff"

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  day1:
    main:                Day1.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent2021

tests:
  day1-test:
    main:                Day1Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent2021
